### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danny98m** [danny98m/GluGo2.0#1]
# ROADMAP

## Near Futre
- [ ] Convert JSON to CSV
- [ ] Create pandas data frame of glucose values
- [ ] Convert glucose values to mg/dL
- [ ] Add other needed factors to data frame
- [ ] Export data in some way decided upon later

## Distant Future
This will consist of the actual algorithm, potential databasing, further data collecting.
Essentially anything we have yet to discover we need.
